WEIGHT_SCALE = 100.0
WEIGHT_BIAS = 0.5
BATCH_NORM_MOMENTUM = 0.8

IMAGE_DIMENSION_X = 64
IMAGE_DIMENSION_Y = IMAGE_DIMENSION_X
IMAGE_DIMENSION_Z = IMAGE_DIMENSION_X

MODEL_CHECKPOINT = "weights.hdf5"

TFRECORD_FOLDER = "/docs/src/kt/datasets/ct-150/tfrecords/{}x{}x{}/".format(IMAGE_DIMENSION_X, IMAGE_DIMENSION_Y, IMAGE_DIMENSION_Z)
